# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mokan\OneDrive\Softwares\LabelU\UI\mainwindows.ui',
# licensing of 'C:\Users\mokan\OneDrive\Softwares\LabelU\UI\mainwindows.ui' applies.
#
# Created: Tue Jul 16 20:14:27 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
import imagesources_rc
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        self.menuAnnotations = QtWidgets.QMenu(self.menu_Tools)
        self.menuAnnotations.setObjectName("menuAnnotations")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetAnnotation = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetAnnotation.sizePolicy().hasHeightForWidth())
        self.dockWidgetAnnotation.setSizePolicy(sizePolicy)
        self.dockWidgetAnnotation.setMinimumSize(QtCore.QSize(200, 308))
        self.dockWidgetAnnotation.setObjectName("dockWidgetAnnotation")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxMode = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBoxMode.setMinimumSize(QtCore.QSize(0, 81))
        self.groupBoxMode.setObjectName("groupBoxMode")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxMode)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 22, 87, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_view = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_view.setObjectName("radioButton_view")
        self.verticalLayout.addWidget(self.radioButton_view)
        self.radioButton_view_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_view_2.setObjectName("radioButton_view_2")
        self.verticalLayout.addWidget(self.radioButton_view_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.groupBoxMode, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.dockWidgetContents_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.tableView_metadata = QtWidgets.QTableView(self.page_3)
        self.tableView_metadata.setObjectName("tableView_metadata")
        self.gridLayout_7.addWidget(self.tableView_metadata, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout_2.addWidget(self.treeWidget, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_clear = QtWidgets.QPushButton(self.page_4)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_5.addWidget(self.pushButton_clear)
        self.pushButton_add = QtWidgets.QPushButton(self.page_4)
        self.pushButton_add.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_5.addWidget(self.pushButton_add)
        self.pushButton_option = QtWidgets.QPushButton(self.page_4)
        self.pushButton_option.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_option.setObjectName("pushButton_option")
        self.horizontalLayout_5.addWidget(self.pushButton_option)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_load = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load.sizePolicy().hasHeightForWidth())
        self.pushButton_load.setSizePolicy(sizePolicy)
        self.pushButton_load.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_6.addWidget(self.pushButton_load)
        self.pushButton_save = QtWidgets.QPushButton(self.page_4)
        self.pushButton_save.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_6.addWidget(self.pushButton_save)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.dockWidgetAnnotation.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetAnnotation)
        self.dockWidgetNavigation = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetNavigation.setObjectName("dockWidgetNavigation")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_leftup = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_leftup.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_148.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_leftup.setIcon(icon)
        self.pushButton_leftup.setObjectName("pushButton_leftup")
        self.gridLayout_3.addWidget(self.pushButton_leftup, 0, 0, 1, 1)
        self.pushButton_up = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_up.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_149.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_up.setIcon(icon1)
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout_3.addWidget(self.pushButton_up, 0, 1, 1, 1)
        self.pushButton_rightup = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_rightup.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_150.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_rightup.setIcon(icon2)
        self.pushButton_rightup.setObjectName("pushButton_rightup")
        self.gridLayout_3.addWidget(self.pushButton_rightup, 0, 2, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_left.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_147.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_left.setIcon(icon3)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout_3.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_right.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_143.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_right.setIcon(icon4)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout_3.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.pushButton_leftdown = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_leftdown.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_146.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_leftdown.setIcon(icon5)
        self.pushButton_leftdown.setObjectName("pushButton_leftdown")
        self.gridLayout_3.addWidget(self.pushButton_leftdown, 2, 0, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_down.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_145.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_down.setIcon(icon6)
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout_3.addWidget(self.pushButton_down, 2, 1, 1, 1)
        self.pushButton_rightdown = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_rightdown.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_144.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_rightdown.setIcon(icon7)
        self.pushButton_rightdown.setObjectName("pushButton_rightdown")
        self.gridLayout_3.addWidget(self.pushButton_rightdown, 2, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 79, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 79, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 2, 0, 1, 1)
        self.dockWidgetNavigation.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetNavigation)
        self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.dockWidgetContents_6)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.graphicsView_overview = QtWidgets.QGraphicsView(self.page)
        self.graphicsView_overview.setObjectName("graphicsView_overview")
        self.gridLayout_5.addWidget(self.graphicsView_overview, 1, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.gridLayout_6.addWidget(self.stackedWidget_2, 0, 0, 1, 1)
        self.dockWidget_4.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_019.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon8)
        self.action_Open.setObjectName("action_Open")
        self.action_Close = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_123.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Close.setIcon(icon9)
        self.action_Close.setObjectName("action_Close")
        self.action_Quit = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon10)
        self.action_Quit.setPriority(QtWidgets.QAction.HighPriority)
        self.action_Quit.setObjectName("action_Quit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_201.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon11)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRectangleAnnotation = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/Middle/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRectangleAnnotation.setIcon(icon12)
        self.actionRectangleAnnotation.setObjectName("actionRectangleAnnotation")
        self.actionPolygonAnnotation = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/Middle/poly.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolygonAnnotation.setIcon(icon13)
        self.actionPolygonAnnotation.setObjectName("actionPolygonAnnotation")
        self.actionSpineAnnotation = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/Middle/spline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpineAnnotation.setIcon(icon14)
        self.actionSpineAnnotation.setObjectName("actionSpineAnnotation")
        self.actionDotAnnotation = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/Middle/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDotAnnotation.setIcon(icon15)
        self.actionDotAnnotation.setObjectName("actionDotAnnotation")
        self.actionDotsetAnnotation = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/Middle/pointset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDotsetAnnotation.setIcon(icon16)
        self.actionDotsetAnnotation.setObjectName("actionDotsetAnnotation")
        self.actionPolygonRnn = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_039.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolygonRnn.setIcon(icon17)
        self.actionPolygonRnn.setObjectName("actionPolygonRnn")
        self.action_About = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_126.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About.setIcon(icon18)
        self.action_About.setObjectName("action_About")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/Small/icon100_com_200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon19)
        self.actionRedo.setObjectName("actionRedo")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Close)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Edit.addAction(self.actionUndo)
        self.menu_Edit.addAction(self.actionRedo)
        self.menuAnnotations.addAction(self.actionRectangleAnnotation)
        self.menuAnnotations.addAction(self.actionPolygonAnnotation)
        self.menuAnnotations.addAction(self.actionSpineAnnotation)
        self.menuAnnotations.addAction(self.actionDotAnnotation)
        self.menuAnnotations.addAction(self.actionDotsetAnnotation)
        self.menuAnnotations.addSeparator()
        self.menuAnnotations.addAction(self.actionPolygonRnn)
        self.menu_Tools.addAction(self.menuAnnotations.menuAction())
        self.menu_About.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.action_Close)
        self.toolBar.addAction(self.action_Quit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRectangleAnnotation)
        self.toolBar.addAction(self.actionPolygonAnnotation)
        self.toolBar.addAction(self.actionSpineAnnotation)
        self.toolBar.addAction(self.actionDotAnnotation)
        self.toolBar.addAction(self.actionDotsetAnnotation)
        self.toolBar.addAction(self.actionPolygonRnn)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.menu_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menu_Edit.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Edit", None, -1))
        self.menu_Tools.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Tools", None, -1))
        self.menuAnnotations.setTitle(QtWidgets.QApplication.translate("MainWindow", "Annotations", None, -1))
        self.menu_About.setTitle(QtWidgets.QApplication.translate("MainWindow", "&About", None, -1))
        self.menuWindows.setTitle(QtWidgets.QApplication.translate("MainWindow", "Windows", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.dockWidgetAnnotation.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Annotation Management", None, -1))
        self.groupBoxMode.setTitle(QtWidgets.QApplication.translate("MainWindow", "Mode", None, -1))
        self.radioButton_view.setText(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.radioButton_view_2.setText(QtWidgets.QApplication.translate("MainWindow", "Annotation", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Detail", None, -1))
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Color", None, -1))
        self.treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Group", None, -1))
        self.treeWidget.headerItem().setText(2, QtWidgets.QApplication.translate("MainWindow", "Type", None, -1))
        self.pushButton_clear.setText(QtWidgets.QApplication.translate("MainWindow", "clear", None, -1))
        self.pushButton_add.setText(QtWidgets.QApplication.translate("MainWindow", "add", None, -1))
        self.pushButton_option.setText(QtWidgets.QApplication.translate("MainWindow", "option", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Annotation", None, -1))
        self.pushButton_load.setText(QtWidgets.QApplication.translate("MainWindow", "load", None, -1))
        self.pushButton_save.setText(QtWidgets.QApplication.translate("MainWindow", "save", None, -1))
        self.dockWidgetNavigation.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Navigator", None, -1))
        self.dockWidget_4.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "OverMap", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "overview", None, -1))
        self.action_Open.setText(QtWidgets.QApplication.translate("MainWindow", "&Open", None, -1))
        self.action_Close.setText(QtWidgets.QApplication.translate("MainWindow", "&Close", None, -1))
        self.action_Quit.setText(QtWidgets.QApplication.translate("MainWindow", "&Quit", None, -1))
        self.action_Quit.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Quit LabelU", None, -1))
        self.actionUndo.setText(QtWidgets.QApplication.translate("MainWindow", "&Undo", None, -1))
        self.actionRectangleAnnotation.setText(QtWidgets.QApplication.translate("MainWindow", "Rectangle Annotation", None, -1))
        self.actionPolygonAnnotation.setText(QtWidgets.QApplication.translate("MainWindow", "Polygon Annotation", None, -1))
        self.actionSpineAnnotation.setText(QtWidgets.QApplication.translate("MainWindow", "Spine Annotation", None, -1))
        self.actionDotAnnotation.setText(QtWidgets.QApplication.translate("MainWindow", "Dot Annotation", None, -1))
        self.actionDotsetAnnotation.setText(QtWidgets.QApplication.translate("MainWindow", "Dotset Annotation", None, -1))
        self.actionPolygonRnn.setText(QtWidgets.QApplication.translate("MainWindow", "PolygonRnn++", None, -1))
        self.action_About.setText(QtWidgets.QApplication.translate("MainWindow", "&About...", None, -1))
        self.actionRedo.setText(QtWidgets.QApplication.translate("MainWindow", "&Redo", None, -1))

# import imagesources_rc

if __name__ == "__main__":
    print("Start!")
    QApp = QtWidgets.QApplication()
    print("Running...")
    mainwindow = QtWidgets.QMainWindow()
    window = Ui_MainWindow()
    window.setupUi(mainwindow)
    window.retranslateUi(mainwindow)
    mainwindow.show()
    print("Done.")
    sys.exit(QApp.exec_())

